In [6]:
import numpy as np
# Columns: Salary | Experience (Years) | Performance Score
salary = np.array([ [25000, 2, 80], 
                    [45000, 5, 90], 
                    [30000, 3, 75], 
                    [60000, 8, 95],
                    [35000, 4, 85] ])
# 1. How will you calculate the average salary of all employees?
avg_salary=np.average(salary[:,0])
print(avg_salary)

39000.0


In [7]:
# 2. How will you find the highest salary?
highest_sal=np.max(salary[:,0])
print(highest_sal)

60000


In [8]:
# 3. How will you find the lowest salary?
lowest_sal=np.min(salary[:,0])
print(lowest_sal)


25000


In [9]:
# 4. How will you calculate the average experience?
avg_exprice=np.average(salary[:,1])
print(avg_exprice)
                

4.4


In [15]:
# 5. How will you find employees whose salary is greater than ₹40,000?
salary_greater=salary[salary[:,0]>40000]
print(salary_greater)


[[45000     5    90]
 [60000     8    95]]


In [18]:
# 6. How will you find employees whose performance score is greater than 80?
performance_score=salary[salary[:,2]>80]
print(performance_score)


[[45000     5    90]
 [60000     8    95]
 [35000     4    85]]


In [20]:
# 7. How will you find the employee with the highest performance score?
high_performance=salary[salary[:,2]==np.max(salary[:,2])]
print(high_performance)

[[60000     8    95]]


In [21]:
# 8. How will you calculate the standard deviation of salaries?
standard_deviation =np.std(salary[:,0])
print(standard_deviation)

12409.673645990857


In [22]:
# 9. How will you classify employees as High Salary or Low Salary using np.where()?
salary_level = np.where(salary[:, 0] >= 40000, "High Salary", "Low Salary")
print(salary_level)


['Low Salary' 'High Salary' 'Low Salary' 'High Salary' 'Low Salary']


In [24]:
# 10. How will you convert the results into a Pandas DataFrame?
import pandas as pd

df = pd.DataFrame(
    salary,
    columns=["Salary", "Experience", "Performance"]
)

df["Salary_Level"] = salary_level

print(df)

   Salary  Experience  Performance Salary_Level
0   25000           2           80   Low Salary
1   45000           5           90  High Salary
2   30000           3           75   Low Salary
3   60000           8           95  High Salary
4   35000           4           85   Low Salary
