In [5]:
import numpy as np
sales = np.array([
 [12000, 15000, 18000],
 [10000, 14000, 16000],
 [18000, 20000, 22000],
 [9000, 12000, 15000],
 [15000, 17000, 19000]
])
# Columns: January | February | March
# 1. How will you calculate the total sales of each salesperson?
total_sale=np.sum(sales,axis=1)
print(total_sale)


[45000 40000 60000 36000 51000]


In [9]:
# 2. How will you calculate the average monthly sales for each salesperson?
avg_monthly=np.average(sales,axis=1)
print(avg_monthly)

[15000.         13333.33333333 20000.         12000.
 17000.        ]


In [11]:
# 3. How will you find the highest sales achieved in each month?
highest_sale=np.max(sales,axis=0)
print(highest_sale)

[18000 20000 22000]


In [12]:
# 4. How will you find the lowest sales achieved in each month?
print(np.min(sales,axis=0))

[ 9000 12000 15000]


In [15]:
# 5. How will you find the salesperson with the highest total sales?
hight_total_sale=np.max(total_sale)
print(hight_total_sale)

60000


In [25]:
# 6. How will you find salespersons whose average sales are above ₹15,000?
avgerage_sale=np.average(sales,axis=1)
# print(avgerage_sale)
avg_sale=sales[avgerage_sale>15000]
print(avg_sale)

[[18000 20000 22000]
 [15000 17000 19000]]


In [26]:
# 7. How will you calculate the total company sales for each month?
total_company=np.sum(sales,axis=0)
print(total_company)


[64000 78000 90000]


In [29]:
# 8. How will you calculate the standard deviation of monthly sales?
standard_deviation=np.std(sales,axis=0)
print(standard_deviation)

[3310.58907145 2727.6363394  2449.48974278]


In [32]:
# 9. How will you classify salespersons as Excellent, Good or Needs Improvement using np.where()?
salespersion=np.where(sales>=18000,"Excellent",
             np.where(sales>=15000,"Good",
                       "Needs Improvement"
                     )
                     )
print(salespersion)

[['Needs Improvement' 'Good' 'Excellent']
 ['Needs Improvement' 'Needs Improvement' 'Good']
 ['Excellent' 'Excellent' 'Excellent']
 ['Needs Improvement' 'Needs Improvement' 'Good']
 ['Good' 'Good' 'Excellent']]


In [36]:
# 10. How will you convert the final results into a Pandas DataFrame?
import pandas as pd
df=pd.DataFrame(
    sales,
    columns=[ "January","February","March"]
)
print(df)

   January  February  March
0    12000     15000  18000
1    10000     14000  16000
2    18000     20000  22000
3     9000     12000  15000
4    15000     17000  19000
