In [5]:
import numpy as np
attendance = np.array([
 [90, 85, 95, 88],
 [75, 80, 70, 78],
 [95, 92, 98, 96],
 [65, 70, 72, 68],
 [85, 88, 90, 87]
])
# Columns: Python | Java | SQL | ML
# 1. How will you calculate the average attendance of each student?
avg_attendance=np.average(attendance,axis=1)
print(avg_attendance)



[89.5  75.75 95.25 68.75 87.5 ]


In [6]:
# 2. How will you calculate the average attendance of each subject?
avg_subject=np.average(attendance,axis=0)
print(avg_subject)

[82.  83.  85.  83.4]


In [7]:
# 3. How will you find the highest attendance in each subject?
print(np.max(attendance,axis=0))


[95 92 98 96]


In [8]:
# 4. How will you find the lowest attendance in each subject?
print(np.min(attendance,axis=0))

[65 70 70 68]


In [11]:
# 5. How will you find students having average attendance above 80%?

result=attendance[avg_attendance>80]
print(result)

[[90 85 95 88]
 [95 92 98 96]
 [85 88 90 87]]


In [13]:
# 6. How will you find the student with the highest average attendance?
hightest_avg=np.max(avg_attendance)
print(hightest_avg)


95.25


In [29]:
# 7. How will you calculate the standard deviation of attendance?
standard_deviation=np.std(attendance)
print(standard_deviation)


10.095915015490176


In [24]:
# 8. How will you use np.where() to classify students as Eligible or Not Eligible based on 75% attendance?
students=np.where(avg_attendance>75,"Eligible","Not Eligible")
print(students)



['Eligible' 'Eligible' 'Eligible' 'Not Eligible' 'Eligible']


In [25]:
# 9. How will you convert the data into a Pandas DataFrame?
import pandas as pd
df=pd.DataFrame(attendance,
              columns=["Python","Java"," SQL"," ML"]
            )
print(df)


   Python  Java   SQL   ML
0      90    85    95   88
1      75    80    70   78
2      95    92    98   96
3      65    70    72   68
4      85    88    90   87


In [30]:
# 10. How will you add a Status column to the DataFrame?
# df=pd.DataFrame(attendance
df["Statuts"]=students
print(df)

   Python  Java   SQL   ML       Statuds       Statuts
0      90    85    95   88      Eligible      Eligible
1      75    80    70   78      Eligible      Eligible
2      95    92    98   96      Eligible      Eligible
3      65    70    72   68  Not Eligible  Not Eligible
4      85    88    90   87      Eligible      Eligible
